server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    password: iissi$user
    url: jdbc:mariadb://localhost:3306/products
    username: iissi_user
  jpa:
    hibernate:
      ddl-auto: update
